# Azure Blob Storage Configuration
azure.storage.connection-string=${azure.storage.connection-string}
azure.storage.container-name=${azure.storage.container-name}

# Azure Table Storage Configuration
azure.table.connection-string=${azure.storage.connection-string}
azure.table.name=${azure.storage.container-name}

# Server Configuration
server.port=8080

# Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB